### PR TITLE
ignore-paths are relative to the composer.json file

### PR DESCRIPTION
**Pull request by olvlvl**
Paths defined with `ignore-paths` are now relative to the composer.json file.

It's a breaking change and requires a major update.

### CODE REVIEW

**Comment by slepic** [comment]
@olvlvl Could the Config properties use camelCase consistently? The `ignore_paths` snake case property seems to stand out of line...

**Comment by olvlvl** [comment]
> Could the Config properties use camelCase consistently?

Yes, it should. Looks like I need to update the linter's config.

**Comment by slepic** [comment]
@olvlvl hello, can you merge this please?

**Comment by olvlvl** [comment]
@slepic I merged the PR. Sorry for the delay.

**Pull request merged**
